# Generated by Django 5.2.4 on 2025-09-26 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSliderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('into', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('position1', models.CharField(blank=True, max_length=50, null=True)),
                ('position2', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='mainSlider')),
                ('thm_text', models.CharField(blank=True, max_length=50, null=True)),
                ('thm_btn', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
