# Generated by Django 5.2.4 on 2025-09-28 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aboutmodel_bestmenuitemmodel_bestmenumodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTableOrderListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('guest', models.CharField(blank=True, max_length=50, null=True)),
                ('massage', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mainslidermodel',
            name='num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
