# Generated by Django 5.2.4 on 2025-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booktableorderlistmodel_mainslidermodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslidermodel',
            name='into4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
