# Generated by Django 5.2.4 on 2025-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mainslidermodel_into4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='into',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
