# Generated by Django 5.2.4 on 2025-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_aboutmodel_into'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='awardImage',
        ),
    ]
