# Generated by Django 5.2.4 on 2025-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_aboutitemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionmodel',
            name='smsImage',
        ),
    ]
