# Generated by Django 5.2.4 on 2025-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_promotionmodel_smsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
