# Generated by Django 5.2.4 on 2025-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_strengthmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthitemmodel',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
