# Generated by Django 5.2.4 on 2025-09-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_strengthitemmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthitemmodel',
            name='image',
        ),
    ]
