# Generated by Django 5.2.4 on 2025-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_strengthitemmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorModel',
        ),
    ]
