# Generated by Django 5.2.4 on 2025-09-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_sponsormodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackitemmodel',
            name='iconImage',
        ),
    ]
