# Generated by Django 5.2.4 on 2025-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_feedbackitemmodel_iconimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='ratemodel',
            name='rate1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ratemodel',
            name='rate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
