# Generated by Django 5.2.4 on 2025-09-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_menumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
