# Generated by Django 5.2.4 on 2025-09-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_menumodel_tag_alter_menumodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestmenuitemmodel',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
