# Generated by Django 5.2.4 on 2025-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bestmenuitemmodel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
