# Generated by Django 5.2.4 on 2025-09-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_aboutmodel_company_aboutmodel_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutitemmodel',
            old_name='title',
            new_name='text',
        ),
    ]
