# Generated by Django 5.2.4 on 2025-10-17 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_product_price_alter_productdetail_disprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='promotionmodel',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='promotionmodel',
            name='min',
        ),
        migrations.RemoveField(
            model_name='promotionmodel',
            name='sec',
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='duration_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
