# Generated by Django 5.2.4 on 2025-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_title_aboutitemmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthitemmodel',
            name='description1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='strengthitemmodel',
            name='description2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='strengthitemmodel',
            name='name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strengthitemmodel',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
