# Generated by Django 5.2.4 on 2025-10-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_promotionmodel_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promotionmodel',
            name='promotion',
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='disPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotionmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
