# Generated by Django 5.2.4 on 2025-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_ratemodel_name1_ratemodel_name2_ratemodel_name3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratemodel',
            old_name='rate13',
            new_name='rate0',
        ),
        migrations.RenameField(
            model_name='ratemodel',
            old_name='rate12',
            new_name='rate22',
        ),
        migrations.RenameField(
            model_name='ratemodel',
            old_name='rate14',
            new_name='rate33',
        ),
        migrations.AddField(
            model_name='ratemodel',
            name='rate44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
