# Generated by Django 5.2.4 on 2025-10-17 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_promotionmodel_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.commentmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/admin/images/no-img-avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
