# Generated by Django 5.2.4 on 2025-09-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_rate13_ratemodel_rate0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratemodel',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='ratemodel',
            name='rate4',
        ),
        migrations.RemoveField(
            model_name='ratemodel',
            name='rate44',
        ),
    ]
