# Generated by Django 5.2.4 on 2025-10-17 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_commentmodel_date_remove_commentmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='content',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=1, primary_key=True, serialize=False),
        ),
    ]
