# Generated by Django 5.2.4 on 2025-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_ratemodel_name4_remove_ratemodel_rate4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestmenumodel',
            old_name='sideImage',
            new_name='Image1',
        ),
        migrations.RenameField(
            model_name='bestmenumodel',
            old_name='topImage',
            new_name='Image2',
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='Image3',
            field=models.ImageField(default='default.jpg', upload_to='BestMenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='Image4',
            field=models.ImageField(default='default.jpg', upload_to='BestMenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='Image5',
            field=models.ImageField(default='default.jpg', upload_to='BestMenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='menu1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='menu2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='menu3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='menu4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bestmenumodel',
            name='menu5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
