# Generated by Django 5.2.4 on 2025-09-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_category1model_category2model_category3model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2Model',
            new_name='Category11Model',
        ),
    ]
