# Generated by Django 5.2.4 on 2025-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_category22model_category2model_category33model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='bImage',
            field=models.ImageField(default=1, upload_to='Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='tImage',
            field=models.ImageField(default='default.jpg', upload_to='Menu'),
            preserve_default=False,
        ),
    ]
