# Generated by Django 5.2.4 on 2025-09-29 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_menuslidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category1', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.ImageField(upload_to='MenuCategory')),
                ('category2', models.CharField(blank=True, max_length=50, null=True)),
                ('image2', models.ImageField(upload_to='MenuCategory')),
                ('category3', models.CharField(blank=True, max_length=50, null=True)),
                ('image3', models.ImageField(upload_to='MenuCategory')),
                ('category4', models.CharField(blank=True, max_length=50, null=True)),
                ('image4', models.ImageField(upload_to='MenuCategory')),
                ('category5', models.CharField(blank=True, max_length=50, null=True)),
                ('image5', models.ImageField(upload_to='MenuCategory')),
                ('category6', models.CharField(blank=True, max_length=50, null=True)),
                ('image6', models.ImageField(upload_to='MenuCategory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menuslidermodel',
            name='image',
            field=models.ImageField(upload_to='MenuSlider'),
        ),
    ]
