# Generated by Django 5.2.4 on 2025-10-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_orderitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
