# Generated by Django 5.2.4 on 2025-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_menucategorymodel_alter_menuslidermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategorymodel',
            name='category11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menucategorymodel',
            name='category22',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menucategorymodel',
            name='category33',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menucategorymodel',
            name='category44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menucategorymodel',
            name='category55',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menucategorymodel',
            name='category66',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
