# Generated by Django 5.2.4 on 2025-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_descriptionmodel_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
