# Generated by Django 5.2.4 on 2025-10-21 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_orderitem_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('guest', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
