# Generated by Django 5.2.4 on 2025-10-02 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_contactslidermodel_newdetailslidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('name11', models.CharField(blank=True, max_length=50, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('name2', models.CharField(blank=True, max_length=50, null=True)),
                ('name22', models.CharField(blank=True, max_length=50, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('name3', models.CharField(blank=True, max_length=50, null=True)),
                ('name33', models.CharField(blank=True, max_length=50, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('name4', models.CharField(blank=True, max_length=50, null=True)),
                ('name44', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
