# Generated by Django 5.2.4 on 2025-10-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_contacttagmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactTagModel',
            new_name='TagModel',
        ),
    ]
