# Generated by Django 5.2.4 on 2025-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_postmodel_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='fb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='linkIn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='p',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
