# Generated by Django 5.2.4 on 2025-10-03 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_profilemodel_fb_profilemodel_linkin_profilemodel_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='New')),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('date1', models.CharField(blank=True, max_length=50, null=True)),
                ('comment1', models.CharField(blank=True, max_length=50, null=True)),
                ('food1', models.CharField(blank=True, max_length=50, null=True)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('description1', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.ImageField(upload_to='New')),
                ('name2', models.CharField(blank=True, max_length=50, null=True)),
                ('date2', models.CharField(blank=True, max_length=50, null=True)),
                ('comment2', models.CharField(blank=True, max_length=50, null=True)),
                ('food2', models.CharField(blank=True, max_length=50, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('description2', models.CharField(blank=True, max_length=50, null=True)),
                ('image2', models.ImageField(upload_to='New')),
                ('name3', models.CharField(blank=True, max_length=50, null=True)),
                ('date3', models.CharField(blank=True, max_length=50, null=True)),
                ('comment3', models.CharField(blank=True, max_length=50, null=True)),
                ('food3', models.CharField(blank=True, max_length=50, null=True)),
                ('title3', models.CharField(blank=True, max_length=50, null=True)),
                ('description3', models.CharField(blank=True, max_length=50, null=True)),
                ('image3', models.ImageField(upload_to='New')),
                ('name4', models.CharField(blank=True, max_length=50, null=True)),
                ('date4', models.CharField(blank=True, max_length=50, null=True)),
                ('comment4', models.CharField(blank=True, max_length=50, null=True)),
                ('food4', models.CharField(blank=True, max_length=50, null=True)),
                ('title4', models.CharField(blank=True, max_length=50, null=True)),
                ('description4', models.CharField(blank=True, max_length=50, null=True)),
                ('image4', models.ImageField(upload_to='New')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
