# Generated by Django 5.2.4 on 2025-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_newmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmodel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='description1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='description2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='description3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='description4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
