# Generated by Django 5.2.4 on 2025-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_newmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='name44',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
