# Generated by Django 5.2.4 on 2025-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_newmodel_name44'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmodel',
            name='image4',
        ),
        migrations.AddField(
            model_name='newmodel',
            name='video3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newmodel',
            name='video4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
