# Generated by Django 5.2.4 on 2025-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_newmodel_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='New'),
            preserve_default=False,
        ),
    ]
