# Generated by Django 5.2.4 on 2025-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
