# Generated by Django 5.2.4 on 2025-10-03 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_commentmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDetailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text1', models.CharField(blank=True, max_length=500, null=True)),
                ('text3', models.CharField(blank=True, max_length=500, null=True)),
                ('text4', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('text5', models.CharField(blank=True, max_length=500, null=True)),
                ('text6', models.CharField(blank=True, max_length=500, null=True)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('text7', models.CharField(blank=True, max_length=500, null=True)),
                ('text8', models.CharField(blank=True, max_length=500, null=True)),
                ('text9', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='NewDetail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
