# Generated by Django 5.2.4 on 2025-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_newdetailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdetailmodel',
            name='text2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
