# Generated by Django 5.2.4 on 2025-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_newdetailmodel_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdetailmodel',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='NewDetail'),
            preserve_default=False,
        ),
    ]
