# Generated by Django 5.2.4 on 2025-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_newdetailmodel_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdetailmodel',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
