# Generated by Django 5.2.4 on 2025-10-03 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_newdetailmodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDetailTagModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('fb', models.CharField(blank=True, max_length=500, null=True)),
                ('x', models.CharField(blank=True, max_length=500, null=True)),
                ('linkIn', models.CharField(blank=True, max_length=500, null=True)),
                ('ig', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
