# Generated by Django 5.2.4 on 2025-10-04 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_aboutexperiencemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('description1', models.CharField(blank=True, max_length=400, null=True)),
                ('name2', models.CharField(blank=True, max_length=50, null=True)),
                ('description2', models.CharField(blank=True, max_length=400, null=True)),
                ('name3', models.CharField(blank=True, max_length=50, null=True)),
                ('description3', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
