# Generated by Django 5.2.4 on 2025-10-04 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_aboutusmodel_alter_aboutslidermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUsModel',
        ),
    ]
