from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    path('', views.HomePage, name="homePage"),
    path('menu/', views.MenuPage, name="menuPage"),
    path('shop/', views.ShopPage, name="shopPage"),
    path('shopDetail/<uuid:pk>/', views.ShopDetailPage, name='shopDetailPage'),
    path('new/', views.NewPage, name="newPage"),
    path('newDetail/', views.NewDetailPage, name="newDetailPage"),
    path('comments/', views.comment_list, name='comment_list'),
    path('comment/post/', views.post_comment, name='post_comment'),
    path('comment/post/<uuid:parent_id>/', views.post_comment, name='post_reply'),
    path('contact/', views.ContactPage, name="contactPage"),
    path('about/', views.AboutPage, name="aboutPage"),
    path('cart/', views.cart_page, name='cartPage'),
    path('cart/add/<uuid:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<uuid:cart_item_id>/',views.remove_from_cart, name='removeFromCart'),
    path('cart/update/<uuid:cart_item_id>/<str:action>/',views.update_cart_quantity, name='updateCart'),
    path('wishlist/move/<uuid:product_id>/', views.move_to_cart, name='move_to_cart'),
    path('wishlist/', views.WishListPage, name='WishListPage'),
    path('wishlist/add/<uuid:product_id>/',views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<uuid:product_id>/',views.remove_from_wishlist, name='remove_from_wishlist'),
    path('checkOut/', views.CheckOutPage, name="checkOutPage"),
    path('checkout/', views.checkout_view, name='checkout'),
    path('order_success/', views.order_success_view, name='order_success'),
    path('order_success/delete/<uuid:order_id>/', views.delete_order, name='delete_order'),
    path('order_success/delete_all/', views.delete_all_orders, name='delete_all_orders'),
    path('login/', views.LoginPage, name='loginPage'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.RegisterPage, name="registerPage"),
    path('book-a-table/', views.book_a_table_view, name='book_a_table'),
    path('search/', views.search_view, name='search'),
]
